'latex_home': 'Latex/datasets_paper/'
'latex_figs': 'Latex/datasets_paper/nogit_data/fig/'
 # for exporting values from python to include in latex
'latex_vars_file': 'Latex/datasets_paper/nogit_data/latex_vars.data'